# fly.toml app configuration file generated for friendshipgaming on 2023-05-26T10:11:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "friendshipgaming"
primary_region = "dfw"

[deploy]
  release_command = "npm run seed"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
